### ISSUE TITLE
export.py: AttributeError: 'dict' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by pyllyukko** [libyal/winevt-kb#15]
While trying to run `export.py` (ae85a49747df63c14b0fa0c577e26d302863c291) with Python 3.6.9, I'm getting this:

```
Traceback (most recent call last):
  File "scripts/export.py", line 567, in <module>
    if not Main():
  File "scripts/export.py", line 560, in Main
    exporter.Export(options.source, output_writer)
  File "scripts/export.py", line 211, in Export
    source_path, database_reader, output_writer)
  File "scripts/export.py", line 120, in _ExportMessageFiles
    output_writer.WriteMessageFile(message_file)
  File "scripts/export.py", line 349, in WriteMessageFile
    self._WriteMessageTable(message_table)
  File "scripts/export.py", line 306, in _WriteMessageTable
    for identifier, string in message_table.message_strings.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

**Comment by joachimmetz** [comment]
thx for the report. Replaced calls to iteritems() in https://github.com/libyal/winevt-kb/commit/8df7829d0bc59984b7f48398b15e12706c6328d2
