### ISSUE TITLE
fix issue

### ISSUE THREAD

**Issue by joachimmetz** [libyal/winevt-kb#5]
```
[INFO] Processing: C:\Program Files\VMware\VMware Tools\Guest SDK\vmStatsProvider\win64\vmStatsProviderMsgs.dll
[WARNING] Missing message file key for: C:\Program Files\VMware\VMware Tools\Guest SDK\vmStatsProvider\win64\vmStatsProviderMsgs.dll
[WARNING] Missing message file key for: C:\Program Files\VMware\VMware Tools\Guest SDK\vmStatsProvider\win64\vmStatsProviderMsgs.dll
Traceback (most recent call last):
  File "winevt-kb/extract.py", line 1083, in <module>
    if not Main():
  File "winevt-kb/extract.py", line 1064, in Main
    extractor.ExtractEventLogMessageStrings(output_writer)
  File "winevt-kb/extract.py", line 531, in ExtractEventLogMessageStrings
    event_log_provider, message_file, normalized_message_filename)
  File "winevt-kb/extract.py", line 884, in WriteMessageFile
    database_writer.WriteResources()
  File "winevt-kb/database.py", line 950, in WriteResources
    self._WriteMessageTables()
  File "winevt-kb/database.py", line 800, in _WriteMessageTables
    self._message_resource_file, message_table, language_identifier)
  File "winevt-kb/database.py", line 732, in _WriteMessageTable
    self._WriteMessageTableLanguage(message_file_key, language_identifier)
  File "winevt-kb/database.py", line 770, in _WriteMessageTableLanguage
    language_identifier, message_file_key)ValueError: Unknown format code 'd' for object of type 'unicode'
```

**Comment by joachimmetz** [comment]
File and product versions appear to be missing.
